groups:
  - name: stocksteward-slo
    rules:
      - alert: MarketMoversHighLatencyP95
        expr: histogram_quantile(0.95, sum(rate(stocksteward_api_request_latency_seconds_bucket{path="/api/v1/market/movers"}[5m])) by (le)) > 1.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "p95 latency too high for /api/v1/market/movers"
          description: "p95 latency exceeded 1.5s for 10 minutes."

      - alert: MarketAnalysisHighLatencyP95
        expr: histogram_quantile(0.95, sum(rate(stocksteward_api_request_latency_seconds_bucket{path="/api/v1/enhanced-ai/market-analysis"}[5m])) by (le)) > 4
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "p95 latency too high for /api/v1/enhanced-ai/market-analysis"
          description: "p95 latency exceeded 4s for 10 minutes."

      - alert: ExternalCallFailureRateHigh
        expr: sum(rate(stocksteward_external_calls_total{status="failure"}[5m])) / clamp_min(sum(rate(stocksteward_external_calls_total[5m])), 1) > 0.05
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "External provider failure rate above 5%"
          description: "External calls failure ratio is above 5% for 10 minutes."

